Base: Ensure that AttributeAuthority requires 1 AttributeService.
Relating to issue #128 an AttributeAuthority could previously get
away with having no or no functioning AttributeService endpoints.

This resulted in invalid XML validation as follows:

    INFO  XmlSecTool - Reading XML document from file 'registry-tamaki-metadata-no-aa-endpoint.xml'
    INFO  XmlSecTool - XML document parsed and is well-formed.
    ERROR XmlSecTool - Invalid XML schema files, unable to validate XML
    org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'NameIDFormat'. One of '{"urn:oasis:names:tc:SAML:2.0:metadata":ContactPerson, "urn:oasis:names:tc:SAML:2.0:metadata":AttributeService}' is expected.